# Generated by Django 2.2.dev20180621213648 on 2018-11-08 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('resumen', models.CharField(max_length=300)),
                ('icono', models.ImageField(upload_to='iconos')),
            ],
        ),
        migrations.CreateModel(
            name='Leccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('resumen', models.CharField(max_length=300)),
                ('icono', models.ImageField(upload_to='iconos')),
            ],
        ),
        migrations.AddField(
            model_name='itemleccion',
            name='leccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fuente_Pagina.Leccion'),
        ),
    ]
