# Generated by Django 2.1.2 on 2018-11-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fuente_Pagina', '0002_leccion_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='leccion',
            name='url',
            field=models.SlugField(default='xd', max_length=100),
            preserve_default=False,
        ),
    ]
