# Generated by Django 2.1.2 on 2018-11-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fuente_Pagina', '0003_leccion_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leccion',
            name='titulo',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
